Test/time actions
senecajs/seneca-telemetry-newrelic pull request #3
Opened 2022-04-27 08:41 UTC by guhmerces

2022-04-27 08:44 UTC, guhmerces commented
Adding info:

![image](https://user-images.githubusercontent.com/45415308/165478958-270c8a7d-60d9-4483-8bd4-9f796d6ba954.png)

2022-04-28 10:34 UTC, rjrodger commented
Did you have to create test or developer newrelic account to validate this? does it generate reports/charts?

2022-05-05 12:14 UTC, rjrodger requested changes

2022-05-09 07:47 UTC, guhmerces commented on create_config_file.js
> +function createNewRelicConfigFile(callback) {
Absolutely. I tried to automate the process but there isn't much to do. Like you mentioned, is a external config that's done manually.

2022-05-09 07:47 UTC, guhmerces commented on package.json
>      "trello": "^0.11.0"
yes, done

2022-05-09 07:48 UTC, guhmerces commented on test/basic.js
> +function newSegment(actionCb) {
This one is out of date. For the moment, I calling the newrelic API methods directly

2022-05-09 07:49 UTC, guhmerces commented on test/basic.js
> +    .message('a:1', startTransaction(
out of date
discussion extended in slack 

thanks

2022-05-09 07:54 UTC, guhmerces commented
I've created a new PR. Perhaps this pr should be closed ?

2022-05-25 19:04 UTC, closed without merging